# Generated by Django 4.2.13 on 2024-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_lang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Език'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_name',
            field=models.CharField(max_length=100, verbose_name='Име на филма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_plot',
            field=models.TextField(blank=True, help_text='кратко описание на филма', null=True, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='film',
            name='movie_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Година'),
        ),
    ]
