# Generated by Django 4.2.13 on 2024-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_film_movie_genre_alter_film_movie_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='baners', verbose_name='Снимка'),
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='films', verbose_name='Снимка'),
        ),
    ]
